config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :orders
  resource :cart
  resources :projects

  resources :products do
    resources :order_items
  end

  root 'projects#index'

  get 'info',                     to: 'projects#info'
  get 'photography',              to: 'projects#photography'

  get 'archives',                 to: 'projects#archives'
  
  get 'design',                   to: 'projects#design'
  get 'lookbook',                 to: 'projects#lookbook'
  get 'contact',                  to: 'projects#contact'
  get 'projects',                 to: 'projects#projects'
  get 'all',                      to: 'projects#all'

  get 'shop',                     to: 'products#index'
end

app/models/project.rb
class Project < ApplicationRecord
  validates :title, presence: true
  validates :artist, presence: true
  validates :description, presence: true
  validates :image_1, presence: true

  mount_uploader :image_1, ImageUploader
  mount_uploader :image_2, ImageUploader
  mount_uploader :image_3, ImageUploader
  mount_uploader :image_4, ImageUploader
  mount_uploader :image_5, ImageUploader
  mount_uploader :image_6, ImageUploader
  mount_uploader :image_7, ImageUploader
  mount_uploader :image_8, ImageUploader
  mount_uploader :image_9, ImageUploader
  mount_uploader :image_10, ImageUploader
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    
  end

  def show
    @project = Project.find(params[:id])
    @prev = Project.where("id < ?", params[:id]).order(:id).last
    @next = Project.where("id > ?", params[:id]).order(:id).first
  end

  def info
    @projects = Project.where(is_team_member: true)
  end

  # def projects
  #  @projects = Project.all
  # end

  def lookbook
    @projects = Project.where(is_lookbook: true)
  end

  def photography
    @projects = Project.where(is_photography: true)
  end

  def design
    @projects = Project.where(is_design: true)
  end

  def archives
    @projects = Project.where(is_archived: true)
  end

  def contact

  end

  def all
    @projects = Project.all
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/all.html.erb
<section class="background-text">
  <%= image_tag("logoglobe.png") %>
</section>

<section class="projects mt">
  <div class="container">
    <div class="project_imgs grid">
      <% @projects.each do |project| %>
          <div>
              <%= image_tag project.image_1.medium.url %>
          </div>
          <% if project.image_2.present? %>
          <div>
              <%= image_tag project.image_2.medium.url %>
          </div>
          <% end %>

            <% if project.image_3.present? %>
            <div>
                <%= image_tag project.image_3.medium.url %>
              </div>
            <% end %>

            <% if project.image_4.present? %>
            <div>
                <%= image_tag project.image_4.medium.url %>
              </div>
            <% end %>

            <% if project.image_5.present? %>
            <div>
                <%= image_tag project.image_5.medium.url %>
                </div>
            <% end %>
      <% end %>
    </div>
  </div>
</section>

app/views/projects/archives.html.erb
<section class="background-text">
  <%= image_tag("logoglobe.png") %>
</section>

<section class="projects mt">
  <div class="container">
    <div class="project_imgs grid">
      <% @projects.each do |project| %>
          <div>
              <%= image_tag project.image_1.medium.url %>
          </div>
          <% if project.image_2.present? %>
          <div>
              <%= image_tag project.image_2.medium.url %>
          </div>
          <% end %>

            <% if project.image_3.present? %>
            <div>
                <%= image_tag project.image_3.medium.url %>
              </div>
            <% end %>

            <% if project.image_4.present? %>
            <div>
                <%= image_tag project.image_4.medium.url %>
              </div>
            <% end %>

            <% if project.image_5.present? %>
            <div>
                <%= image_tag project.image_5.medium.url %>
                </div>
            <% end %>
      <% end %>
    </div>
  </div>
</section>

app/views/projects/contact.html.erb
<section class="contact mt">
  <div class="container">
      <div class="card">
        <h4>Contact Us</h4><br />
        <form action="https://formspree.io/contact@dreamhi.us" method="POST">
          <input type="text" name="name" placeholder="Your Name" class="btn" style="width: 90%;">
          <input type="hidden" name="_subject" value="New Inquiry!" style="width: 90%;"/>
          <input type="email" name="_replyto" placeholder="Your Email" class="btn" style="width: 90%;">
          <textarea type="text" name="message" placeholder="Your Message" class="btn" style="height: 200px; width: 90%; min-width: 120px;"></textarea>
          <input type="submit" value="Send" class="btn" style="min-width: 80px;">
        </form>
      </div>
      <div class="card">
        <h4>Join Our Mailing List</h4><br />
        <form action="https://formspree.io/contact@dreamhi.us" method="POST">
          <input type="hidden" name="_subject" value="New Email Submission!" style="width: 90%;"/>
          <input type="email" name="_replyto" placeholder="Your Email" class="btn" style="width: 90%;">
          <input type="submit" value="Sign Up" class="btn">
        </form>
      </div>
      <!--
      <div class="card mobile">
        <h4>Hit Us Up</h4><br />
        <nav>
          <%= mail_to "contact@dreamhi.us", 'Email', class: "btn"%>
          <%= link_to "Instagram", "https://www.instagram.com/dreamhiiii/", target: '_blank', class: "btn"%>
          <%= link_to "Twitter", "https://www.twitter.com/dreamhiiii/", target: '_blank', class: "btn"%>
        </nav>
      </div>
      -->
  </div>
</section>

app/views/projects/design.html.erb
<section class="background-text">
  <%= image_tag("logoglobe.png") %>
</section>

<section class="projects mt">
  <div class="container">
    <div class="project_imgs grid">
      <% @projects.each do |project| %>
          <div>
            <%= link_to project_path(project) do %>
              <%= image_tag project.image_1.medium.url %>
            <% end %>
          </div>
          <% if project.image_2.present? %>
          <div>
            <%= link_to project_path(project) do %>
              <%= image_tag project.image_2.medium.url %>
            <% end %>
          </div>
          <% end %>

            <% if project.image_3.present? %>
            <div>
              <%= link_to project_path(project) do %>
                <%= image_tag project.image_3.medium.url %>
              <% end %>
              </div>
            <% end %>

            <% if project.image_4.present? %>
            <div>
              <%= link_to project_path(project) do %>
                <%= image_tag project.image_4.medium.url %>
              <% end %>
              </div>
            <% end %>

            <% if project.image_5.present? %>
            <div>
              <%= link_to project_path(project) do %>
                <%= image_tag project.image_5.medium.url %>
              <% end %>
                </div>
            <% end %>
      <% end %>
    </div>
  </div>
</section>

app/views/projects/index.html.erb
<section class='intro'>
  <div class="container">
    <div class="image">
      <%= image_tag('logo-full.png')%>
    </div>
    
    <ul>
      <li><%= link_to 'lookbook', lookbook_path, class: "btn"%><%= link_to 'shop', shop_path, class: "btn"%></li>
      <li><%= link_to 'photography', photography_path, class: "btn"%><%= link_to 'all', all_path, class: "btn"%></li>
      <li><%= link_to 'design', design_path, class: "btn"%><%= link_to 'archive', archives_path, class: "btn"%></li>
      <li><%= link_to 'info', info_path , class: "btn"%><%= link_to 'contact', contact_path , class: "btn"%></li>
    </ul>
  </div>
</section>

app/views/projects/info.html.erb
<section class="projects info team mt">
  <div class="container">
      <div class="card">
          <%= image_tag("logo-full.png", :alt => "DREAMHI", class: "logo") %>
          <h3>Drēm/Hī/</h3>
          <h4>Take A Chance</h4><br />
          <p>DreamHi is a creative brand consulting agency and apparel brand. Our team helps build artist brands by providing marketing consulting that is a custom fit for each artist’s needs. With our experience in the global music and fashion industries, we analyze strengths and weaknesses and put forward a plan toward reaching the artist’s brand dreams. </p><br />
          <p>Our apparel brand offers tour merchandising which includes concept, design, and production. </p><br />
          <p>The DreamHi team works with artists to create honest and authentic products that provide the perfect connection between fans and artists. All merchandise is created with in-house graphics, photography, and designers. </p>
      </div>
      
      <div class="team-grid">
        <% @projects.each do |project| %>
            <div class="team">
                <%= image_tag project.image_1.medium.url %>
                <div class="card">
                  <h4><%= project.artist %></h4>
                  <h5><%= project.title %></h5>
                  <p><%= project.description %></p>
                </div>
            </div>
        <% end %>
      </div>
    </div>
</section>

app/views/projects/lookbook.html.erb
<section class="background-text">
    <%= image_tag("logoglobe.png") %>
</section>

<section class="projects mt">
    <div class="container">
        <div class="card video-card">
            <iframe width="100%" height="500px" src="https://www.youtube.com/embed/c5rYRNV-sl0" controls="0" frameborder="0" autoplay="1" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
        <div class="lookbook_imgs grid">
            <% @projects.each do |project| %>
                <div> <%= image_tag project.image_1.medium.url %> </div>

                <% if project.image_2.present? %>
                    <div> <%= image_tag project.image_2.medium.url %> </div>
                <% end %>

                <% if project.image_3.present? %>
                    <div> <%= image_tag project.image_3.medium.url %> </div>
                <% end %>

                <% if project.image_4.present? %>
                    <div> <%= image_tag project.image_4.medium.url %> </div>
                <% end %>

                <% if project.image_5.present? %>
                    <div> <%= image_tag project.image_5.medium.url %> </div>
                <% end %>

                <% if project.image_6.present? %>
                    <div> <%= image_tag project.image_6.medium.url %>  </div>
                <% end %>

                <% if project.image_7.present? %>
                    <div> <%= image_tag project.image_7.medium.url %> </div>
                <% end %>

                <% if project.image_8.present? %>
                    <div> <%= image_tag project.image_8.medium.url %> </div>
                <% end %>

                <% if project.image_9.present? %>
                    <div> <%= image_tag project.image_9.medium.url %> </div>
                <% end %>

                <% if project.image_10.present? %>
                    <div> <%= image_tag project.image_10.medium.url %> </div>
                <% end %>
            <% end %>
        </div>
    </div>
</section>

app/views/projects/photography.html.erb
<section class="background-text">
  <%= image_tag("logoglobe.png") %>
</section>

<section class="projects mt">
  <div class="container">
    <div class="project_imgs grid">
      <% @projects.each do |project| %>
          <div>
            <%= link_to project_path(project) do %>
              <%= image_tag project.image_1.medium.url %>
            <% end %>
          </div>
          <% if project.image_2.present? %>
          <div>
            <%= link_to project_path(project) do %>
              <%= image_tag project.image_2.medium.url %>
            <% end %>
          </div>
          <% end %>

            <% if project.image_3.present? %>
            <div>
              <%= link_to project_path(project) do %>
                <%= image_tag project.image_3.medium.url %>
              <% end %>
              </div>
            <% end %>

            <% if project.image_4.present? %>
            <div>
              <%= link_to project_path(project) do %>
                <%= image_tag project.image_4.medium.url %>
              <% end %>
              </div>
            <% end %>

            <% if project.image_5.present? %>
            <div>
              <%= link_to project_path(project) do %>
                <%= image_tag project.image_5.medium.url %>
              <% end %>
                </div>
            <% end %>
      <% end %>
    </div>
  </div>
</section>

app/views/projects/projects.html.erb
<h1>hi</h1>



<!-->
<section class="background-text">
  <%= image_tag("logoglobe.png") %>
</section>

<section class="projects mt">
  <div class="container">
    <div class="project_imgs grid">
      <% @projects.each do |project| %>
          <div>
            <%= link_to project_path(project) do %>
              <%= image_tag project.image_1.medium.url %>
            <% end %>
          </div>
          <% if project.image_2.present? %>
          <div>
            <%= link_to project_path(project) do %>
              <%= image_tag project.image_2.medium.url %>
            <% end %>
          </div>
          <% end %>

            <% if project.image_3.present? %>
            <div>
              <%= link_to project_path(project) do %>
                <%= image_tag project.image_3.medium.url %>
              <% end %>
              </div>
            <% end %>

            <% if project.image_4.present? %>
            <div>
              <%= link_to project_path(project) do %>
                <%= image_tag project.image_4.medium.url %>
              <% end %>
              </div>
            <% end %>

            <% if project.image_5.present? %>
            <div>
              <%= link_to project_path(project) do %>
                <%= image_tag project.image_5.medium.url %>
              <% end %>
                </div>
            <% end %>
      <% end %>
    </div>
  </div>
</section>

app/views/projects/show.html.erb
<section class="background-text">
  <%= image_tag("logoglobe.png") %>
</section>

<section class='project mt'>
  <div class="container projects-show">
      <div class="images">
        <%= image_tag @project.image_1.large.url%>
        <% if @project.image_2.present? %>
          <%= image_tag @project.image_2.large.url%>
        <% end %>
        <% if @project.image_4.present? %>
          <%= image_tag @project.image_4.large.url%>
        <% end %>
        <% if @project.image_5.present? %>
          <%= image_tag @project.image_5.large.url%>
        <% end %>
        <% if @project.image_3.present? %>
          <%= image_tag @project.image_3.large.url%>
        <% end %>
        <% if @project.image_4.present? %>
          <%= image_tag @project.image_4.large.url%>
        <% end %>
        <% if @project.image_5.present? %>
          <%= image_tag @project.image_5.large.url%>
        <% end %>
      </div>

      <div class="card show-card">
          <h4><%= @project.title%></h4>
          <h5 style="font-weight:700;"><%=@project.artist%></h5><br />
          <p><%= simple_format @project.description %></p><br />

          <div class='navlinks'>
            <% if @prev %>
              <%= link_to "Prev", @prev, class: "btn" %>
            <% else %>
              <%= link_to "Prev", '#', :class => "strike btn"%>
            <% end %>

            <% if @next %>
              <%= link_to "Next", @next, class: "btn" %>
            <% else %>
              <%= link_to "Next", '#', :class => "strike btn"%>
            <% end %>
          </div>
        </div>
    </div>
</section>

<style>
.images { padding-bottom: 500px; }
footer { display: none; }
</style>