config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :orders
  resource :cart
  resources :projects

  resources :products do
    resources :order_items
  end

  root 'projects#index'

  get 'info',                     to: 'projects#info'
  get 'photography',              to: 'projects#photography'

  get 'archives',                 to: 'projects#archives'
  
  get 'design',                   to: 'projects#design'
  get 'lookbook',                 to: 'projects#lookbook'
  get 'contact',                  to: 'projects#contact'
  get 'projects',                 to: 'projects#projects'
  get 'all',                      to: 'projects#all'

  get 'shop',                     to: 'products#index'
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :order_items

  def total_quantity
    @count = 0

    order_items.all.each do |item|
      @count = @count + item.quantity
    end

    @count
  end

  def total_price
    @total = 0

    order_items.all.each do |item|
      @total = @total + item.product.price * item.quantity
    end

    @total
  end

  def total_price_in_dollars
    @total = 0

    order_items.all.each do |item|
      @total = @total + item.product.price_in_dollars * item.quantity
    end

    @total

  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show

  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.erb
<section class="cart mt">
  <div class="container">
      <div class="order-summary">
        <h2>Order Summary</h2>

        <% if @current_cart.order_items.any? %>
        <div class="cart-items">
          <% @current_cart.order_items.each do |item| %>
            <div class="cart-item card">
              <%= image_tag item.product.image_1.url %>
              <h3><%= item.product.title %></h3>
              <h4><%= number_to_currency item.product.price, precision: 0 %></h4><br>

              <%= simple_form_for [item.product, item] do |f| %>
                <h5>Size: </h5><%= f.input :size, collection: ["XS", "S", "M","L","XL"], label: false, required: true %>
                <h5>Quantity: </h5><%= f.input :quantity, label: false, collection: ["1", "2", "3","4","5"] %>
                <%= f.button :submit, "Update" %>
              <% end %>
              
              <%= link_to "Delete?", product_order_item_path(item.product, item), method: :delete %>
            </div>
          <% end %>
        </div>
        <%= link_to "Continue to Checkout", new_order_path, class: 'checkout-btn' %>





        <% else %>
          <b><h5 class="empty"> There are no items in your cart! </h5></b>
        <% end %>
      </div>
  </div>
</section>