config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :orders
  resource :cart
  resources :projects

  resources :products do
    resources :order_items
  end

  root 'projects#index'

  get 'info',                     to: 'projects#info'
  get 'photography',              to: 'projects#photography'

  get 'archives',                 to: 'projects#archives'
  
  get 'design',                   to: 'projects#design'
  get 'lookbook',                 to: 'projects#lookbook'
  get 'contact',                  to: 'projects#contact'
  get 'projects',                 to: 'projects#projects'
  get 'all',                      to: 'projects#all'

  get 'shop',                     to: 'products#index'
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_items

  validates :title, presence: true
  validates :price, presence: true
  validates :description, presence: true
  # validates :image_1, presence: true

  mount_uploader :image_1, ProductImageUploader
  mount_uploader :image_2, ProductImageUploader
  mount_uploader :image_3, ProductImageUploader
  mount_uploader :image_4, ProductImageUploader
  mount_uploader :image_5, ProductImageUploader

  def price_in_dollars
    price / 100
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @prev = Product.where("id < ?", params[:id]).order(:id).last
    @next = Product.where("id > ?", params[:id]).order(:id).first

    @order_item = @current_cart.order_items.find_by(product: @product)

    if @order_item.nil?
      @order_item = @current_cart.order_items.new(product: @product, quantity: 1)
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<div class="alert"><p>Free Dreamhi Dice With Every Purchase While Supplies Last</p></div>
<section class="products mt">
  <div class="container">
    <div class="products-grid">
      <% @products.each do |product| %>
        <% if product.is_sold_out==true %>
          <div class="sold-out product">
            <%= image_tag product.image_1.medium.url, class: "image"%>
            <h5><%= product.title%></h5>
            <p><%= number_to_currency product.price, precision: 0%></p>
            <div class="overlay">
              <div class="text"><h2>SOLD OUT</h2></div>
            </div>
          </div>
        <% else %>
          <div class="product">
            <%= link_to product_path(product) do %>
              <%= image_tag product.image_1.medium.url %>
              <h5><%= product.title%></h5>
              <p><%= number_to_currency product.price, precision: 0%></p>
            <% end %>
          </div>
        <% end %>
      <% end %>
  </div>
  </div>
</section>

app/views/products/show.html.erb
<div class="alert"><p>Free Dreamhi Dice With Every Purchase While Supplies Last</p></div>

<section class='product mt show-page'>
  <div class="container">
      <div class="images">
        <%= image_tag @product.image_1.large.url%>
        <% if @product.image_2.present? %>
          <%= image_tag @product.image_2.large.url %>
        <% end %>
        <% if @product.image_4.present? %>
          <%= image_tag @product.image_4.large.url %>
        <% end %>
        <% if @product.image_5.present? %>
          <%= image_tag @product.image_5.large.url %>
        <% end %>
        <% if @product.image_3.present? %>
          <%= image_tag @product.image_3.large.url %>
        <% end %>
        <% if @product.image_4.present? %>
          <%= image_tag @product.image_4.large.url %>
        <% end %>
        <% if @product.image_5.present? %>
          <%= image_tag @product.image_5.large.url %>
        <% end %>
      </div>

      <div class=" card product-card">
        <h3><%= @product.title%></h3>
        <h5><%= number_to_currency @product.price, precision: 0 %></h5><br>
        <p><%= simple_format @product.description %></p>
        <% if @product.description_2.present?%>
        <p><b><%= simple_format @product.description_2 %></b></p>
        <% end %>

        <%= simple_form_for [@product, @order_item] do |f|%>
          <div class="buttons">
            <br />
              <div class="size">
                <h5><b>Size:</b></h5>
                <%= f.input :size, collection: ["XS", "S", "M","L","XL"], selected: "S", required: true, label: false %>
              </div>
              <div class="quantity">
                <h5><b>Quantity:</b></h5>
                <%= f.input :quantity, collection: ["1", "2", "3","4","5"], label: false %>
              </div>
                <%= f.button :submit, 'Add to Cart'%>
          </div>
        <% end %>

        <div class='navlinks'>
          <% if @prev %>
            <%= link_to "Prev", @prev, class: "btn" %>
          <% else %>
            <%= link_to "Prev", '#', :class => "strike btn"%>
          <% end %>

          <% if @next %>
            <%= link_to "Next", @next, class: "btn" %>
          <% else %>
            <%= link_to "Next", '#', :class => "strike btn"%>
          <% end %>
        </div>
      </div>



  </div>
</section>