config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :orders
  resource :cart
  resources :projects

  resources :products do
    resources :order_items
  end

  root 'projects#index'

  get 'info',                     to: 'projects#info'
  get 'photography',              to: 'projects#photography'

  get 'archives',                 to: 'projects#archives'
  
  get 'design',                   to: 'projects#design'
  get 'lookbook',                 to: 'projects#lookbook'
  get 'contact',                  to: 'projects#contact'
  get 'projects',                 to: 'projects#projects'
  get 'all',                      to: 'projects#all'

  get 'shop',                     to: 'products#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dreamhi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="https://js.stripe.com/v3/"></script>
    <%= javascript_include_tag 'application' %>

    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <%= stylesheet_link_tag 'application', media: 'all'%>
  </head>

  <body>
  <div class="grid-bkgrd">
   <!-- <%= image_tag("grid4.png") %> -->
  </div>
    <% if flash[:success].present? %>
      <div class='success flash'>
        <%= flash[:success]%>
      </div>
    <% end %>
    <% if flash[:error].present? %>
      <div class='error flash'>
        <%= flash[:error]%>
      </div>
    <% end %>
    <% if flash[:alert].present? %>
      <div class='alert flash'>
        <b><%= flash[:alert]%></b>
      </div>
    <% end %>

    <header>
    <div class="container">
        <%= link_to image_tag('logo-globe.png'), root_path, class: "logo btn"%>
        <div class='search-cart'>
          <%= link_to 'shop', shop_path, class: "btn"%>
          <%= link_to cart_path do %>
            <div class='cart btn'>
              <%= @current_cart.total_quantity%>
            </div>
          <% end %>
        </div>
      </div>
    </header>



    <%= yield %>
    <footer>
      <div class="container">
        <nav>
          <%= mail_to "contact@dreamhi.us", 'Email', class: "btn"%>
          <%= link_to "Instagram", "https://www.instagram.com/dreamhiiii/", target: '_blank', class: "btn"%>
          <%= link_to "Twitter", "https://www.twitter.com/dreamhiiii/", target: '_blank', class: "btn"%>
        </nav>
        <form action="https://formspree.io/info@dreamhi.com" method="POST">
          <input type="email" name="_replyto" placeholder="Your Email" class="btn">
          <input type="submit" value="Submit" class="btn">
        </form>
        <div class="bottom-text">
          <p>&copy; 2019 Dreamhi</p>
          <%= link_to "Site Created by b.", "https://www.brianagude.com/", target: '_blank', class: 'bri-text'%> 
        </div>
      </div>
    </footer>

    <%= javascript_include_tag 'application' %>
  </body>
</html>